language: node_js
node_js:
  - "8"
script:
 - echo "Deploying!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase target:apply hosting flutter-ieeethapar flutter-ieeethapar
  - firebase deploy --project ieeethapar --token $FIREBASE_TOKEN